env:
  es6: true
  node: true
  amd: true
extends:
  - './node_modules/gts/'
parserOptions:
  ecmaVersion: 2019
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  no-process-exit:
    - off
