(print
 (and
  (eq? '() '())
  (not (eq? '() '(1 2)))
  (not (eq? '(1 2) '(1 2)))
  (eq? #f #f)
  (eq? #t #t)
  (not (eq? #f #t))
  (eq? 'foo 'foo)
  (not (eq? 'foo 'bar))

  (equal? '() '())
  (not (equal? '() '(1 2)))
  (equal? '(1 2) '(1 2))
  (equal? #f #f)
  (equal? #t #t)
  (not (equal? #f #t))
  (equal? 2 2)
  (not (equal? 2 3))
  (equal? 'foo 'foo)
  (not (equal? 'foo 'bar))

  (null? '())
  (not (null? '(1 2)))
  (not (null? #t))
  (not (null? 28))
  (not (null? 'foo))

  (not (pair? '()))
  (pair? '(1 2))
  (not (pair? #t))
  (not (pair? 28))
  (not (pair? 'foo))

  (not (boolean? '()))
  (not (boolean? '(1 2)))
  (boolean? #t)
  (not (boolean? 28))
  (not (boolean? 'foo))

  (not (integer? '()))
  (not (integer? '(1 2)))
  (not (integer? #t))
  (integer? 28)
  (not (integer? 'foo))

  (not (symbol? '()))
  (not (symbol? '(1 2)))
  (not (symbol? #t))
  (not (symbol? 28))
  (symbol? 'foo)))
