env:
  es6: true
  node: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2019
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - args: none
  max-len:
    - error
    - code: 80
  no-new-object:
    - error
  no-array-constructor:
    - error
  no-new-wrappers:
    - error
  no-multi-str:
    - error
  no-with:
    - error
  no-console:
    - off
  no-shadow-restricted-names:
    - off
