name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bash:
    name: Bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile and run tests
      run: bash/run_tests.sh
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Compile and run tests
      run: go/run_tests.sh
  haskell:
    name: Haskell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
    - name: Compile and run tests
      run: haskell/run_tests.sh
  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Compile and run tests
      run: javascript/run_tests.sh
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Compile and run tests
      run: python/run_tests.sh
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Compile and run tests
      run: python/run_tests.sh
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Compile and run tests
      run: typescript/run_tests.sh
  reference:
    name: Reference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Gauche
      run: sudo apt-get install -y --no-install-recommends gauche
    - name: Compile and run tests
      run: reference/run_tests.sh
